### PR TITLE
Add a translation to French

### PR DESCRIPTION
**Pull request by kekh**
Hi,

Here is a new translation to French. I can't test it because even after modifying build.linux.sh & resource.qrc it does not show up in the UI... But anyway, it should be correct (this is my native language).
So would you please make appropriate changes to make it appear in the UI that I can validate for good this small contribution to your wonderful work?

Thank you!

### CODE REVIEW

**Comment by abbat** [comment]
Thanks!

**Comment by abbat** [comment]
Build released - added new translation to UI. Thanks again!

**Comment by kekh** [comment]
You're welcome ! Thanks to you !

...on another subject and just to know, do you have (by chance) any plans about a "Sync daemon" feature or maybe the integration of the Yandex-cli functionalities in your great UI?

**Comment by abbat** [comment]
No, I don't plan to copy official cli functions (because its already realized). May be sync/backup **on demand** but not automatic to mirror any file (its very hard to implement on millions files). For on demand (cron) backups/sync you can try [ydcmd](https://github.com/abbat/ydcmd) console client.

**Comment by kekh** [comment]
Oh too bad, I do not think it was so complicated to act as a frontend by running Yandex-cli commands in the background :-/
But ok I'll try [ydcmd](https://github.com/abbat/ydcmd) and also [yandex-disk-indicator](https://github.com/slytomcat/yandex-disk-indicator) which is much closer of what I need.

**Pull request merged**
